# DROP TABLE STATEMENTS
online_retail_table_drop = "DROP TABLE IF EXISTS core.OnlineRetail"
stocks_table_drop = "DROP TABLE IF EXISTS core.Stocks"
invoices_table_drop = "DROP TABLE IF EXISTS core.Invoices"
date_table_drop = "DROP TABLE IF EXISTS core.Date"
country_table_drop = "DROP TABLE IF EXISTS core.country"

# CREATE TABLE STATEMENTS
online_retail_table_create = ("""CREATE TABLE IF NOT EXISTS 
                                         core.OnlineRetail(retail_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT 1 START 1) PRIMARY KEY,
                                                    stock_id int REFERENCES core.Stocks(stock_id),
                                                    invoice_id int REFERENCES core.Invoices(invoice_id), 
                                                    date_id int REFERENCES core.Date(date_id),
                                                    country_id integer REFERENCES core.Country(country_id), 
                                                    customer_id int, 
                                                    quantity int,
                                                    unit_price float);
""")

stocks_table_create = ("""CREATE TABLE IF NOT EXISTS 
                                        core.Stocks(stock_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT 1 START 1) PRIMARY KEY, 
                                                stock_code varchar(25), 
                                                stock_name varchar);
""")

invoices_table_create = ("""CREATE TABLE IF NOT EXISTS 
                                        core.Invoices(invoice_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT 1 START 1) PRIMARY KEY, 
                                                 invoice_no varchar);
""")

date_table_create = ("""CREATE TABLE IF NOT EXISTS 
                                        core.Date(date_id int PRIMARY KEY, 
                                             invoice_date timestamp);
""")

country_table_create = ("""CREATE TABLE IF NOT EXISTS 
                                        core.Country(country_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT 1 START 1) PRIMARY KEY, 
                                                    country_name varchar);
""")


# INSERT STATEMENTS
online_retail_table_insert = ("""INSERT INTO core.OnlineRetail(stock_id, invoice_id, date_id, country_id, customer_id, quantity, unit_price)
                        VALUES(%s,%s,%s,%s,%s,%s,%s)
                        ON CONFLICT
                        DO NOTHING;
""")

stocks_table_insert = ("""INSERT INTO core.Stocks(stock_code, stock_name)
                        VALUES(%s,%s)
                        ON CONFLICT
                        DO NOTHING;
""")

invoices_table_insert = ("""INSERT INTO core.Invoices(invoice_no)
                        VALUES(%s)
                        ON CONFLICT
                        DO NOTHING;
""")

date_table_insert = ("""INSERT INTO core.Date(date_id, invoice_date)
                          VALUES(%s,%s)
                          ON CONFLICT
                          DO NOTHING;
""")

country_table_insert = ("""INSERT INTO core.Country(country_name)
                        VALUES(%s)
                        ON CONFLICT
                        DO NOTHING;
""")

#STAGING SCHEMA EXECUTION
create_staging_schema = """CREATE SCHEMA IF NOT EXISTS staging;"""
create_core_schema = """CREATE SCHEMA IF NOT EXISTS core;"""

#CREATE STAGING TABLES
create_staging_retail_table = """CREATE TABLE IF NOT EXISTS staging.retail(InvoiceNo varchar, StockCode varchar, Description varchar, Quantity int, InvoiceDate timestamp, UnitPrice float, CustomerID int, Country varchar);"""

#DROP STAGING TABLES
staging_retail_table_drop = "DROP TABLE IF EXISTS staging.retail"

#INSERT STAGING TABLES
staging_retail_table_insert = ("""INSERT INTO 
                                staging.retail(InvoiceNo,
                                                StockCode,
                                                Description,
                                                Quantity,
                                                InvoiceDate,
                                                UnitPrice,
                                                CustomerID,
                                                Country                  
)VALUES(%s,%s,%s,%s,%s,%s,%s,%s)""")


# QUERY LISTS FOR EXECUTION
create_schema_queries = [create_staging_schema, create_core_schema]
create_table_queries = [create_staging_retail_table, stocks_table_create, invoices_table_create, date_table_create, country_table_create, online_retail_table_create]
drop_table_queries = [staging_retail_table_drop, stocks_table_drop, invoices_table_drop, date_table_drop, country_table_drop, online_retail_table_drop]
